### 课程计划绑定视频
POST {{content_host}}/media/teachplan/association/media
Content-Type: application/json

{
  "mediaId": "",
  "fileName": "",
  "teachplanId": ""
}


### 课程计划接触视频绑定
DELETE {{content_host}}/teachplan/association/media/332/135
